apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: osso
build:
  artifacts:
  - image: registry.dev.scimmia.net/osso
    docker:
      cacheFrom:
        - osso-build
        - osso-image
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
